pool:
    vmImage: 'ubuntu-latest' 
steps:
    - script: docker login -u appsvcbuildacr -p $(acrPassword) appsvcbuildacr.azurecr.io
    - script: git clone $(gitURL)
    - script: docker build --no-cache -t appsvcbuildacr.azurecr.io/$(imageTag) $(gitURL)
      timeoutInMinutes: 180
    - script: docker push appsvcbuildacr.azurecr.io/$(imageTag)
