steps:
- script: git clone $(gitURL)
- script: docker build -t appsvcbuildacr.azurecr.io/$(imageTag) $(gitURL)
- script: docker login -u appsvcbuildacr -p $(acrPassword) appsvcbuildacr.azurecr.io
- script: docker push appsvcbuildacr.azurecr.io/$(imageTag)

