pool:
    vmImage: 'ubuntu-latest' 
steps:
    - script: docker login -u appsvcbuildacr -p $(acrPassword) appsvcbuildacr.azurecr.io
    - script: git clone $(gitURL)
    - script: cd $(repoName)
    - script: git fetch origin
    - script: git checkout origin/$(branchName)
    - bash: |
        if [[ "$(useCache)" -eq "True" ]]
        then
            docker build -t appsvcbuildacr.azurecr.io/$(imageTag) .
        else
            docker build --no-cache -t appsvcbuildacr.azurecr.io/$(imageTag) .
        fi
      timeoutInMinutes: 180
    - script: docker push appsvcbuildacr.azurecr.io/$(imageTag)
