pool:
    vmImage: 'ubuntu-latest' 
steps:
    - bash: |
        docker login -u appsvcbuildacr -p $(acrPassword) appsvcbuildacr.azurecr.io
        git clone $(gitURL)
        cd $(repoName)
        git fetch origin
        git checkout origin/$(branchName)
        if [[ "$(useCache)" -eq "True" ]]
        then
            docker build -t appsvcbuildacr.azurecr.io/$(imageTag) .
        else
            docker build --no-cache -t appsvcbuildacr.azurecr.io/$(imageTag) .
        fi
      timeoutInMinutes: 180
    - script: docker push appsvcbuildacr.azurecr.io/$(imageTag)
